------------------------------------------------------------------------
title: R_GIS_HW04
author: Derek Ding 
date: "`r Sys.Date()`" 
output: html_document
code_folding: show
------------------------------------------------------------------------

# Week 4 HW

## 0. Homework objective:
- Read in global [gender inequality](https://hdr.undp.org/data-center/documentation-and-downloads) data
- Join the global gender inequality index to [spatial data of the World](https://hub.arcgis.com/datasets/2b93b06dc0dc4e809d3c8db5cb96ba69_0/explore?location=-0.111978%2C0.000000%2C1.00), creating a new column of difference in inequality between 2010 and 2019 
- Share it with the World on GitHub

## 1. Load libraries and Import Data

In this assignment we will use the following libraries:

### 1.1 Libraries
```{r echo= TRUE, error=TRUE}
library(sf)
library(tidyverse)
# library(dplyr)
library(shiny)
library(tmap)
library(tmaptools)
library(readxl)
library(sf)
library(here)
library(leaflet)
library(raster)
library(dplyr)
library(terra)
```


```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```


```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```


```{r echo= TRUE, error=TRUE}

```



```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```


```{r echo= TRUE, error=TRUE}

```


```{r echo= TRUE, error=TRUE}

```







```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```


```{r echo= TRUE, error=TRUE}

```



```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```


```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

```{r echo= TRUE, error=TRUE}

```

